In [ ]:
from pathlib import Path
from mutagen.mp4 import MP4
import pandas as pd
target_dir = Path(r'data\Brainrot')

if target_dir.exists():
    print(True)

df = pd.DataFrame()

for ind, item in enumerate(target_dir.iterdir()):
    mp4 = MP4(item)
    dct = {
    'title': f'Brainrot_{ind}',
    'bitrate': mp4.info.bitrate,
    'length': mp4.info.length,
    'sample_rate': mp4.info.sample_rate,
    'channels': mp4.info.channels
    }

    df_t = pd.DataFrame([dct])
    df = pd.concat([df,df_t],ignore_index=True)

True
        title  bitrate      length  sample_rate  channels
0  Brainrot_0   128031   60.093243        44100         2
1  Brainrot_1   128026   60.093243        44100         2
2  Brainrot_2   128041   60.070023        44100         2
3  Brainrot_3   127999  117.191111        44100         2
4  Brainrot_4   127999   83.800816        44100         2

In [ ]:
import os

for ind, file in enumerate(target_dir.iterdir()):

    rep_name = f'data\Brainrot\Brainrot_{ind}.mp4'
    os.rename(file, rep_name, src_dir_fd=None, dst_dir_fd=None)
    print(file)

<>:5: SyntaxWarning: invalid escape sequence '\B'
<>:5: SyntaxWarning: invalid escape sequence '\B'
C:\Users\nikit\AppData\Local\Temp\ipykernel_10424\592397336.py:5: SyntaxWarning: invalid escape sequence '\B'
  rep_name = f'data\Brainrot\Brainrot_{ind}'

data\Brainrot\1 Minute of Gen Alpha Brainrot Part 3.mp4
data\Brainrot\1 Minute of Gen Alpha Brainrot.mp4
data\Brainrot\1_58 Of plain BrainRot compilation.mp4
data\Brainrot\2023 Anthem - Rizzler Music Video brain rot edition.mp4
data\Brainrot\3rd graders after someone says sigma skibdi toilet gyatt rizz in ohio.mp4
data\Brainrot\A RAM SAM SAM OMEGA NUGGET roblox coemsroblox funny robloxcoems omega omeganugget robloxfunny.mp4
data\Brainrot\Addressing the allegations....mp4
data\Brainrot\ALL COUPLES Italian Brainrot Animals Compilation.mp4
data\Brainrot\ALL Indonesian Anomali Brainrot AI Animals Compilation _ Tung Tung Tung Sahur.mp4
data\Brainrot\ALL Italian Brainrot AI Animals Battles _ Fights Compilation.mp4
data\Brainrot\ALL Italian Brainrot AI Animals Compilation _ Tralalero Tralala.mp4
data\Brainrot\ALWAYS LOVE YOUR MOM shorts.mp4
data\Brainrot\Avatar- Iroh give zuko a speech - meme.mp4
data\Brainrot\BIRTH to DEATH of BRAINROT In Adopt Me Roblox shorts.mp4
data\Brainrot\Bombardino Crocodilo but in 4K Original Meme Italian Brainrot.mp4
data\Brainrot\BOMBARDINO CROCODILO Original vs Translate English Translation Version _ Italian Brainrot.mp4
data\Brainrot\BOMBARDINO CROCODILO vs ALL Italian Brainrot AI Animals Compilation.mp4
data\Brainrot\Bombombini Gusini but in 4K Original Italian Brainrot Meme Translation Bombombini Guzzini.mp4
data\Brainrot\Brain rot then vs now nostalgia nostalgic brainrot.mp4
data\Brainrot\Brainrot Churchill.mp4
data\Brainrot\British Grandma sings Down in Ohio ohio onlyinohio grandma downinohio swaglikeohio.mp4
data\Brainrot\bro turned into ai tiktok.mp4
data\Brainrot\Cant let the homies know.mp4
data\Brainrot\Commercials Trying To Be _Hip With The Kids_ 2.mp4
data\Brainrot\Commercials Trying To Be _Hip With The Kids_.mp4
data\Brainrot\concerts in 2050 capcut meme memes skibiditoilet brainrot.mp4
data\Brainrot\Did Gen Z Or Gen Alpha Have A Harder Remix_ Fortnite etc. shorts genz genalpha fortnite.mp4
data\Brainrot\did messi really just say this__.mp4
data\Brainrot\Did you disrespect Skibidi toilet_.mp4
data\Brainrot\Did you disrespect skibidi toilet__1.mp4
data\Brainrot\dont rizz me. dont come by ohio..mp4
data\Brainrot\Drake Diss.mp4
data\Brainrot\drake drake go away but cartman sings it.mp4
data\Brainrot\drake drake go away but skibidi toilet kendrick sings it.mp4
data\Brainrot\Dutchs Final Speech but its Brainrot.mp4
data\Brainrot\Eminem - Rizz YourselfTrailer.mp4
data\Brainrot\erm what the sigma.mp4
data\Brainrot\every sigma edit.mp4
data\Brainrot\Fella was praying to the Skibidi gods.mp4
data\Brainrot\filter filters funny skibidi gyatt ohio rizz rizzler.mp4
data\Brainrot\First I gyatt your brother now I rizz you FNAF_VHS.mp4
data\Brainrot\Gegagedigedagedago Help Dog Pass Nikocado Avocado Challenge with Chocolate in Toilet.mp4
data\Brainrot\Gegagedigedagedago.mp4
data\Brainrot\gen alpha is getting out of handkungfupanda.mp4
data\Brainrot\Generation Alpha has arrived..mp4
data\Brainrot\GOO GOO GA GA SONG DELETED LANKYBOX MUSIC VIDEO.mp4
data\Brainrot\GOON FU PANDA 2.mp4
data\Brainrot\Grandma singing sticking out your gyatt for the rizzler foryou grandma rizz no.1rizzler.mp4
data\Brainrot\Grimice shake skibidi toilet duke dennis only in ohio rizz gyat lvl 5.mp4
data\Brainrot\GTA 5 Scary Teacher Spiderman Hulk Challenge BIKE RACE ep.79 shorts.mp4
data\Brainrot\GYATT NURSERY RHYME.mp4
data\Brainrot\GYATT SONG.mp4
data\Brainrot\Gyatts Plan - Drake Dennis.mp4
data\Brainrot\HAWK TUAH X LUNCHLY.mp4
data\Brainrot\He Hurt His Arm So I Helped shorts.mp4
data\Brainrot\HE WAS SO CONFUSED shorts.mp4
data\Brainrot\HOW TO BE A SIGMA.mp4
data\Brainrot\How to Make Italian Brainrot Animals Memes_ TUTORIAL.mp4
data\Brainrot\I am worried for generation alpha.mp4
data\Brainrot\I will never love bacon hairs.mp4
data\Brainrot\if avatar is brainrot avatar memes brainrot funny.mp4
data\Brainrot\IMPOSSIBLE CHALLENGE TOWER shorts.mp4
data\Brainrot\Inspirational Story.mp4
data\Brainrot\Invincible Brainrot Edit.mp4
data\Brainrot\iPong 13 Pro Max shorts fyp viral iphone.mp4
data\Brainrot\iron man if it was actually good brain rot edit.mp4
data\Brainrot\Is this the new national anthem_ shorts.mp4
data\Brainrot\Italian Brainrot AI Animals Battles FIGHT.mp4
data\Brainrot\Italian Brainrot AI Animals in 3D Models Download Free.mp4
data\Brainrot\Italian Brainrot Skeleton Compilation Nooo Skeleton Meme _ That One Bro.mp4
data\Brainrot\Its beginning to look a gyatt like Rizzmas.mp4
data\Brainrot\JackSucksAtLife Reacts to His GYAT Tier List.mp4
data\Brainrot\Kai Cenat GYAT COMPILATION subscribe.mp4
data\Brainrot\Kai Cenat Gyat Sound Effect _ Soundboard Link.mp4
data\Brainrot\kai cenat.mp4
data\Brainrot\Kids with Skibidi Toilet Syndrome be like.mp4
data\Brainrot\Level 1 Gyatt vs. Level 2 Gyatt vs. Level 3 Gyatt.mp4
data\Brainrot\Lirili Larila Elephant but in 4K Original Italian Brainrot Meme.mp4
data\Brainrot\literal brain rot memes skibidi brainrot.mp4
data\Brainrot\Little song I wrote viral.mp4
data\Brainrot\LORAX BRAINROTskibiditoilet brainrot memes trending viral edit funny sigma.mp4
data\Brainrot\Lunchly ad but there is a cringe-o-meter.mp4
data\Brainrot\Lunchly Hawk Tuah and KSIs song.mp4
data\Brainrot\mario movie if it was actually good brain rot edit.mp4
data\Brainrot\mazicraft the most brain rot video of 2024 brainrot funny shorts.mp4
data\Brainrot\Messi skibidi toilet VS Ronaldo.mp4
data\Brainrot\Messi toilet Sigma shorts.mp4
data\Brainrot\noob gave me savage replies minecraft gaming bts shorts viral.mp4
data\Brainrot\OHIO Mrbeast VS Catnap Pomni Rank6974 Battle.mp4
data\Brainrot\Ohio NPC explains Looksmaxxing.mp4
data\Brainrot\Ohio sigma skibidi toilet.mp4
data\Brainrot\Ohios skibidi gyatt hells greatest dad gen alpha mix.mp4
data\Brainrot\Oldest skibidi fan _ Skibidi dop dop dop ya ya full video.mp4
data\Brainrot\omega nugget crying.mp4
data\Brainrot\Only 2023 kids will get this.mp4
data\Brainrot\Putin Sings _Skibidi toilet_.mp4
data\Brainrot\Ranking brain rot songs viral.mp4
data\Brainrot\RARE GYATT SIGHTING.mp4
data\Brainrot\ratatouille if it was actually good brain rot edit.mp4
data\Brainrot\Rizzler Tries LUNCHLY.mp4
data\Brainrot\Rizzy dadrizzskibidigyattohioantizoofunny dadmewmewing.mp4
data\Brainrot\roblox coemsroblox funny coems robloxcoems robloxfunny robloxmemes omega omeganugget.mp4
data\Brainrot\RONALDO sus 9999 RANK UP cristianoronaldo siuuuuu ronaldo.mp4
data\Brainrot\RONALDO vs MR BEAST sus amogus EVOLUTION cristianoronaldo mrbeast sus.mp4
data\Brainrot\s skibidi ohio rizz gyatt sigma.mp4
data\Brainrot\Scary Teacher 3d Gaming Doll Squid game troll Team Granny vs Huggy wuggy shorts.mp4
data\Brainrot\Scary Teacher 3D Miss T steal Nick and Tanis diamond ring shorts.mp4
data\Brainrot\SFM SKIBIDI GYATT OHIO RIZZLER FANUM TAX.mp4
data\Brainrot\SHE IS SO KIND shorts LankyBox PLUSHIES.mp4
data\Brainrot\SIGMA MEAL SKIBIDI SLICERS.mp4
data\Brainrot\SIGMA MEALS SKIBIDI SLICERS.mp4
data\Brainrot\Sigma skibidi toilet Ohio.mp4
data\Brainrot\skibidi biden.mp4
data\Brainrot\Skibidi Edge Rizz..mp4
data\Brainrot\Skibidi fortnite sped up lyrics.mp4
data\Brainrot\skibidi ohio rizz gyatt sigma fanum tax.mp4
data\Brainrot\skibidi Ohio sigma gyatt rizz gigachad funny skibidtoilet.mp4
data\Brainrot\skibidi ohio sigma gyatt rizz ligmaballs.mp4
data\Brainrot\Skibidi rizz gyatt Ohio.mp4
data\Brainrot\Skibidi rizz Ohio Gyatt level 10 skibiditoilet skibidi rizz gyat ohio sigma sigmarule memes.mp4
data\Brainrot\skibidi sigma ohio rizz overdose.mp4
data\Brainrot\Skibidi Sigma Pomni Digital fortnite Chamba.mp4
data\Brainrot\Skibidi Toilet Concert.mp4
data\Brainrot\Skibidi Toilet Gyatt Ohio Rizz.mp4
data\Brainrot\skibidi toilet khaby lame messi fede vigevani hasbula steve harvey skibidi skibiditoilet sigma.mp4
data\Brainrot\skibidi toilet level 10 gyatt ohio rizz sigma place shorts australia skibiditoilet rizz ohio.mp4
data\Brainrot\Skibidi Toilet Version CAPIBARA.mp4
data\Brainrot\Skibidi Toilet Will Be Mine creds to rizzlerremix.mp4
data\Brainrot\skibidi toliet in ohio part 1.mp4
data\Brainrot\so skibidibi skibidi skibiditoilet gyatt ohio mewing wrizz sigma rizz funny meme.mp4
data\Brainrot\Spider-Man 3 but he has brainrot.mp4
data\Brainrot\Sticking out you GYATT for the RIZZLER.mp4
data\Brainrot\Sticking out your gyatt for the rizzler.mp4
data\Brainrot\the bops on the bus go hawk tuah ANIMATED BRAIN ROT SONG.mp4
data\Brainrot\The Brain Rot Alphabet brainrot.mp4
data\Brainrot\TikTok live rizz party original video.mp4
data\Brainrot\Toilet paper president in Ohio ohio.mp4
data\Brainrot\TOP 10 Indonesian Brainrot AI Animals Compilation.mp4
data\Brainrot\TOP 10 Italian Brainrot AI Animals Compilation.mp4
data\Brainrot\Top Sigma Quotes.mp4
data\Brainrot\Tralalero Tralala but in 4K Original Meme.mp4
data\Brainrot\Tralalero Tralala Full Family _ Italian Brainrot Animals.mp4
data\Brainrot\Tralalero Tralala FULL Translation in English _ Tralalelotralala ENG Translate Voiceover Version.mp4
data\Brainrot\TRALALERO TRALALA Happy Birthday to You _ Italian Shark Brainrot Meme.mp4
data\Brainrot\Tralalero Tralala vs Bombardino Crocodilo BATTLE ALL FIGHTS.mp4
data\Brainrot\Tralalero Tralala vs Tralalelo Ramadalila Original vs Meme Italian Brainrot Animals.mp4
data\Brainrot\Tralalero Tralala vs Tralalerotralala _ Italian Brainrot AI Animals Battle.mp4
data\Brainrot\Tralalero Tralala x Havana BRAINROT REMIX Camila Cabello.mp4
data\Brainrot\Travis Scott - Skibidi toilet Lyrics.mp4
data\Brainrot\Trulimero Trulichina but in 4K Original Italian Brainrot Meme.mp4
data\Brainrot\try not to brainrot challenge.mp4
data\Brainrot\Tung Tung Tung Sahur but in 4K Original Meme.mp4
data\Brainrot\Tung Tung Tung Sahur SCARY STORY Full Brainrot Episode.mp4
data\Brainrot\ULTIMATE Brain Rot Quiz.mp4
data\Brainrot\wake up in the morning feeling so skibidi.mp4
data\Brainrot\What the 25 - FNAF SECURITY BREACH RUIN ANIMATION _ GHS ANIMATION.mp4
data\Brainrot\what the sigma.mp4
data\Brainrot\What The Sigma_.mp4
data\Brainrot\When she banbaning zaza style on your pizza tower.mp4
data\Brainrot\When you were in Ohio Couldnt look you in the gyatt.mp4
data\Brainrot\Who Will It Be_ FOXY AND BOXY React shorts.mp4
data\Brainrot\Whose performance was better_ Brain Rot Edition.mp4
data\Brainrot\Will He Win_ shorts.mp4
data\Brainrot\Your Rizz _ Oh Oh Ohio FULL VERSION OFFICIAL.mp4
data\Brainrot\_IM THE FAT SIGMA_ - Kung Fu Panda If it was Braintrot Edit _ SDP INTERLUDE.mp4

In [ ]:
df.describe()

             bitrate       length  sample_rate  channels
count     166.000000   166.000000        166.0     166.0
mean   128071.969880    81.426646      44100.0       2.0
std       190.142448   237.411487          0.0       0.0
min    127998.000000     1.811156      44100.0       2.0
25%    127999.000000    14.913016      44100.0       2.0
50%    128017.500000    32.693696      44100.0       2.0
75%    128066.500000    61.428390      44100.0       2.0
max    130069.000000  2300.888526      44100.0       2.0

In [26]:
df[df['length'] > 2290]

          title  bitrate       length  sample_rate  channels
11  Brainrot_11   127999  2300.888526        44100         2