#### Imports

In [1]:
from pathlib import Path
from mutagen.mp4 import MP4
import pandas as pd
import os
import itertools

#### Changing names of files (Single run)

In [2]:
b_target_dir = Path(r'data\Brainrot')
nb_target_dir = Path(r'data\NonBrainrot')


# for ind, file in enumerate(target_dir.iterdir()):

#     rep_name = fr'data\NonBrainrot\NonBrainrot_{ind}.mp4'
#     os.rename(file, rep_name, src_dir_fd=None, dst_dir_fd=None)
#     print(file)

#### Making dataframe with metadata of an mp4 file:

Metadata
- bitrate: file bitrate 
- length: length of a record in mls
- sample_rate: sample rate for a record
- channels: number of audio channels

In [3]:
if b_target_dir.exists() and nb_target_dir.exists():
    print('Both directories are found and loaded')

df = pd.DataFrame()

for ind, item in enumerate(itertools.chain(nb_target_dir.iterdir(), b_target_dir.iterdir())):
    mp4 = MP4(item)

    dct = {
    'title': item.name,
    'bitrate': mp4.info.bitrate,
    'length': mp4.info.length,
    'sample_rate': mp4.info.sample_rate,
    'channels': mp4.info.channels
    }

    df_t = pd.DataFrame([dct])
    df = pd.concat([df,df_t],ignore_index=True)

Both directories are found and loaded

In [8]:
df.to_csv('data/metadata.csv', index=False)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        262 non-null    str
 1   bitrate      262 non-null    int64
 2   length       262 non-null    float64
 3   sample_rate  262 non-null    int64
 4   channels     262 non-null    int64
dtypes: float64(1), int64(3), str(1)
memory usage: 10.4 KB

In [5]:
df.describe()

             bitrate       length  sample_rate  channels
count     262.000000   262.000000        262.0     262.0
mean   128019.484733   201.592544      44100.0       2.0
std       304.403892   339.745628          0.0       0.0
min    125588.000000     1.811156      44100.0       2.0
25%    127999.000000    28.026485      44100.0       2.0
50%    128001.000000    58.700045      44100.0       2.0
75%    128035.750000   234.869841      44100.0       2.0
max    130069.000000  2300.888526      44100.0       2.0

In [6]:
df[df['length'] > 2290]

              title  bitrate       length  sample_rate  channels
98  Brainrot_10.mp4   127999  2300.888526        44100         2